name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step 
        run: echo "Hello World!"
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
        # mail server settings
         server_address: smtp.gmail.com
         server_port: 465
    # user credentials
         username: ${{ secrets.udhaya }}
         password: ${{ secrets.udhaya123 }}
    # email subject
         subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
         body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
         to: er.udhayakumar17091994@gmail.com,udhay171995@gmail.com
    # from email name
         from: udhaya
